package com.ahsanrehmat.pulseplan.domain

import com.ahsanrehmat.pulseplan.model.Exercise

data class ExerciseGuide(
    val targetArea: String,
    val equipment: String,
    val steps: List<String>,
    val commonMistake: String,
)

object ExerciseGuideCatalog {
    private val guides = mapOf(
        "squat" to guide(
            target = "Legs and glutes",
            equipment = "Bodyweight",
            first = "Stand with your feet about shoulder-width apart and brace your middle.",
            second = "Send your hips back and bend your knees within a comfortable range.",
            third = "Press through your whole foot to stand tall with control.",
            mistake = "Letting the knees collapse inward or rushing the lowering phase.",
        ),
        "push_up" to guide(
            target = "Chest, shoulders, arms, and core",
            equipment = "Stable raised surface",
            first = "Place your hands on a secure surface slightly wider than your shoulders.",
            second = "Keep your body in one long line as you lower your chest toward the surface.",
            third = "Press the surface away until your arms are straight without locking hard.",
            mistake = "Dropping the hips or letting the shoulders shrug toward the ears.",
        ),
        "reverse_lunge" to guide(
            target = "Legs, glutes, and balance",
            equipment = "Bodyweight",
            first = "Stand tall, brace gently, and step one foot straight behind you.",
            second = "Lower both knees only as far as you can control while keeping the front foot planted.",
            third = "Drive through the front foot to return to standing, then change sides.",
            mistake = "Stepping onto a tightrope instead of keeping enough width for balance.",
        ),
        "glute_bridge" to guide(
            target = "Glutes and back of the legs",
            equipment = "Floor or exercise mat",
            first = "Lie on your back with knees bent and feet flat about hip-width apart.",
            second = "Brace gently and press through your feet to lift your hips.",
            third = "Pause with the glutes working, then lower slowly without arching the back.",
            mistake = "Pushing the hips too high by over-arching the lower back.",
        ),
        "dead_bug" to guide(
            target = "Core control",
            equipment = "Floor or exercise mat",
            first = "Lie on your back with hips and knees bent and arms reaching upward.",
            second = "Keep your lower back gently connected to the floor as opposite limbs move away.",
            third = "Return with control and repeat on the other side while breathing normally.",
            mistake = "Moving farther than you can control and allowing the lower back to lift.",
        ),
        "plank" to guide(
            target = "Core, shoulders, and glutes",
            equipment = "Floor or exercise mat",
            first = "Place elbows under shoulders and extend your legs behind you.",
            second = "Brace your middle and squeeze your glutes to make one straight line.",
            third = "Hold while taking steady breaths, then lower before your form changes.",
            mistake = "Letting the hips sag or holding your breath.",
        ),
        "db_goblet_squat" to guide(
            target = "Legs, glutes, and core",
            equipment = "One dumbbell",
            first = "Hold one dumbbell close to your chest and stand with stable feet.",
            second = "Sit the hips down and back while keeping the weight close and chest comfortable.",
            third = "Press through the floor to stand without letting the knees cave inward.",
            mistake = "Holding the weight away from the body or losing control at the bottom.",
        ),
        "db_floor_press" to guide(
            target = "Chest, shoulders, and triceps",
            equipment = "Two dumbbells and floor",
            first = "Lie on your back with knees bent and a dumbbell safely held in each hand.",
            second = "Lower the upper arms until they gently meet the floor.",
            third = "Press the dumbbells upward over the chest and stop before they collide.",
            mistake = "Bouncing the arms off the floor or bending the wrists backward.",
        ),
        "db_row" to guide(
            target = "Upper back and arms",
            equipment = "One dumbbell and stable support",
            first = "Support one hand, keep a long neutral spine, and let the dumbbell hang.",
            second = "Pull the elbow toward your back pocket without twisting your torso.",
            third = "Lower the weight fully under control, then finish the side before switching.",
            mistake = "Shrugging the shoulder or rotating the body to move the weight.",
        ),
        "db_rdl" to guide(
            target = "Hamstrings, glutes, and back",
            equipment = "Two dumbbells",
            first = "Stand tall with dumbbells close to the thighs and knees softly bent.",
            second = "Push the hips backward while the weights travel close to your legs.",
            third = "Stop when the hamstrings feel loaded, then drive the hips forward to stand.",
            mistake = "Turning the movement into a squat or rounding the back to reach lower.",
        ),
        "db_press" to guide(
            target = "Shoulders and triceps",
            equipment = "Two dumbbells and stable seat",
            first = "Sit tall with feet planted and hold the dumbbells near shoulder height.",
            second = "Brace gently and press upward without leaning your ribs back.",
            third = "Lower the weights to the starting position with control.",
            mistake = "Over-arching the back or forcing a painful overhead range.",
        ),
        "farmer_carry" to guide(
            target = "Grip, core, shoulders, and full body",
            equipment = "Two dumbbells",
            first = "Stand tall with one dumbbell at each side and shoulders relaxed.",
            second = "Brace your middle and walk with short, quiet, controlled steps.",
            third = "Keep both weights level, then set them down by bending the hips and knees.",
            mistake = "Leaning to one side or letting the weights swing.",
        ),
        "leg_press" to guide(
            target = "Legs and glutes",
            equipment = "Leg press machine",
            first = "Set the seat so your feet are stable and your hips stay against the pad.",
            second = "Lower the platform through a comfortable range with knees tracking over toes.",
            third = "Press evenly through both feet without forcefully locking the knees.",
            mistake = "Lowering so far that the hips curl away from the pad.",
        ),
        "chest_press" to guide(
            target = "Chest, shoulders, and triceps",
            equipment = "Chest press machine",
            first = "Adjust the seat so the handles sit around mid-chest and feet are planted.",
            second = "Press the handles forward while keeping shoulders relaxed against the pad.",
            third = "Return slowly until you feel a comfortable stretch across the chest.",
            mistake = "Letting the shoulders roll forward or snapping the elbows straight.",
        ),
        "lat_pulldown" to guide(
            target = "Upper back and arms",
            equipment = "Lat pulldown machine",
            first = "Sit securely with thighs supported and take a comfortable grip.",
            second = "Keep your chest tall and pull the bar toward the upper chest.",
            third = "Straighten the arms slowly without allowing the weight stack to slam.",
            mistake = "Swinging backward or pulling the bar behind the neck.",
        ),
        "cable_row" to guide(
            target = "Upper back and arms",
            equipment = "Seated cable row",
            first = "Sit tall with feet supported, knees soft, and arms extended.",
            second = "Pull the handle toward your body while guiding elbows close to your sides.",
            third = "Pause briefly, then reach forward under control without rounding deeply.",
            mistake = "Using a large body swing instead of moving through the shoulders and arms.",
        ),
        "hamstring_curl" to guide(
            target = "Back of the thighs",
            equipment = "Hamstring curl machine",
            first = "Adjust the machine so its pivot aligns comfortably with your knee.",
            second = "Curl the pad using the back of the legs while keeping the hips steady.",
            third = "Return slowly until the knees are nearly straight.",
            mistake = "Lifting the hips or letting the weight drop on the return.",
        ),
        "pallof_press" to guide(
            target = "Core and anti-rotation control",
            equipment = "Cable machine",
            first = "Stand sideways to the cable with the handle held at your chest.",
            second = "Brace and press your hands straight forward without turning your torso.",
            third = "Bring the handle back slowly, finish the repetitions, then change sides.",
            mistake = "Allowing the cable to rotate the shoulders or shifting the feet.",
        ),
        "march" to guide(
            target = "Cardio, hips, and coordination",
            equipment = "Bodyweight",
            first = "Stand tall with space around you and begin marching at an easy pace.",
            second = "Lift alternating knees while swinging the opposite arm naturally.",
            third = "Increase speed only while your landings stay quiet and controlled.",
            mistake = "Leaning backward or stamping the feet as fatigue builds.",
        ),
        "step_jack" to guide(
            target = "Cardio and full body",
            equipment = "Bodyweight",
            first = "Stand tall with arms by your sides and knees soft.",
            second = "Step one foot sideways while raising both arms through a comfortable range.",
            third = "Return to center and repeat to the other side at a steady rhythm.",
            mistake = "Turning the step into a jump or forcing the arms overhead.",
        ),
        "squat_reach" to guide(
            target = "Legs, glutes, shoulders, and cardio",
            equipment = "Bodyweight",
            first = "Stand with stable feet and lower into a comfortable squat.",
            second = "Press through the floor to stand while reaching both arms upward.",
            third = "Bring the arms down before beginning the next controlled repetition.",
            mistake = "Leaning backward during the reach or allowing the knees to collapse inward.",
        ),
        "mountain_climber" to guide(
            target = "Core, shoulders, hips, and cardio",
            equipment = "Stable raised surface",
            first = "Place hands on a secure surface and create a straight line through the body.",
            second = "Bring one knee toward the chest without rounding or twisting excessively.",
            third = "Switch legs at a pace that lets the shoulders stay over the hands.",
            mistake = "Bouncing the hips or using a surface that can move.",
        ),
        "skater_step" to guide(
            target = "Legs, hips, balance, and cardio",
            equipment = "Bodyweight",
            first = "Stand tall and step one foot diagonally behind the other.",
            second = "Shift into the front leg while keeping the step low impact and controlled.",
            third = "Push back to center and repeat smoothly on the other side.",
            mistake = "Jumping farther than you can balance or twisting the planted knee.",
        ),
        "slow_burpee" to guide(
            target = "Full body and cardio",
            equipment = "Bodyweight and floor",
            first = "Bend the hips and knees to place your hands on the floor or a raised surface.",
            second = "Step one foot and then the other back into a strong plank.",
            third = "Step forward one foot at a time and stand tall before repeating.",
            mistake = "Rushing the steps until the back sags or balance is lost.",
        ),
        "cat_cow" to guide(
            target = "Spine and trunk mobility",
            equipment = "Floor or exercise mat",
            first = "Start on hands and knees with hands under shoulders and knees under hips.",
            second = "Exhale as you gently round the back and let the head follow naturally.",
            third = "Inhale as you reverse the curve only through a comfortable range.",
            mistake = "Forcing the neck or lower back to create a larger movement.",
        ),
        "world_stretch" to guide(
            target = "Hips, upper back, and legs",
            equipment = "Floor or exercise mat",
            first = "Step into a long lunge and place your hands inside the front foot.",
            second = "Keep the rear leg comfortable while rotating the chest toward the front leg.",
            third = "Return the hand, step back carefully, and repeat on the other side.",
            mistake = "Forcing the rotation or letting the front foot lose stable contact.",
        ),
        "hip_90_90" to guide(
            target = "Hip mobility",
            equipment = "Floor or exercise mat",
            first = "Sit with both knees bent and feet wider than the hips.",
            second = "Rotate both knees toward one side while keeping the movement smooth.",
            third = "Return through center and switch sides without forcing the end position.",
            mistake = "Using momentum or pushing into pinching discomfort at the hip.",
        ),
        "wall_slide" to guide(
            target = "Shoulders and upper back mobility",
            equipment = "Clear wall",
            first = "Stand comfortably against a wall with ribs gently tucked.",
            second = "Place arms against the wall in a bent position without forcing contact.",
            third = "Slide the arms upward through a pain-free range, then lower slowly.",
            mistake = "Arching the lower back to make the arms travel higher.",
        ),
        "ankle_rock" to guide(
            target = "Ankle mobility",
            equipment = "Stable support if needed",
            first = "Stand in a split stance with the front foot fully planted.",
            second = "Guide the front knee forward over the toes while the heel stays down.",
            third = "Return gently and repeat before changing sides.",
            mistake = "Allowing the heel to lift or the arch to collapse inward.",
        ),
        "child_pose" to guide(
            target = "Back, hips, and relaxed breathing",
            equipment = "Floor or exercise mat",
            first = "Start on hands and knees, then move the hips back toward the heels comfortably.",
            second = "Reach the arms forward or rest them wherever your shoulders feel relaxed.",
            third = "Take slow breaths into the sides and back of the ribcage.",
            mistake = "Forcing the hips backward or staying in a position that pinches the knees.",
        ),
        "chair_squat" to guide(
            target = "Legs and glutes",
            equipment = "Stable chair",
            first = "Stand just in front of a chair with feet about shoulder-width apart.",
            second = "Send your hips back until they touch the chair softly without dropping onto it.",
            third = "Press through your whole feet to stand tall with control.",
            mistake = "Falling onto the chair or letting the knees collapse inward.",
        ),
        "wall_push_up" to guide(
            target = "Chest, shoulders, arms, and core",
            equipment = "Clear stable wall",
            first = "Place your hands on the wall slightly wider than your shoulders and step back.",
            second = "Keep your body long as you bend the elbows and bring your chest toward the wall.",
            third = "Press the wall away until the arms are straight without locking hard.",
            mistake = "Letting the hips stay behind while only the upper body moves.",
        ),
        "supported_split_squat" to guide(
            target = "Legs, glutes, and balance",
            equipment = "Stable support",
            first = "Take a split stance and hold a stable support lightly for balance.",
            second = "Keep both feet planted as you lower straight down through a comfortable range.",
            third = "Press through the front foot to rise, then finish the side before switching.",
            mistake = "Using the support to pull yourself up or placing both feet on one narrow line.",
        ),
        "standing_hip_extension" to guide(
            target = "Glutes and hip control",
            equipment = "Stable support",
            first = "Stand tall beside a stable support with weight balanced over one leg.",
            second = "Move the other leg gently behind you without leaning forward or arching.",
            third = "Squeeze the glute briefly, return slowly, then switch sides.",
            mistake = "Swinging the leg or creating the movement by arching the lower back.",
        ),
        "bird_dog" to guide(
            target = "Core, back, and hip stability",
            equipment = "Floor or exercise mat",
            first = "Start on hands and knees with a long neutral spine.",
            second = "Reach one arm and the opposite leg away while keeping the hips level.",
            third = "Return slowly and repeat on the other side without holding your breath.",
            mistake = "Lifting the limbs too high and rotating or arching the torso.",
        ),
        "incline_plank" to guide(
            target = "Core, shoulders, and glutes",
            equipment = "Stable raised surface",
            first = "Place both hands on a secure surface and walk your feet back.",
            second = "Brace gently to create a straight line from shoulders through heels.",
            third = "Hold while breathing steadily and stop before the hips begin to sag.",
            mistake = "Using a surface that can move or letting the shoulders shrug.",
        ),
        "db_split_squat" to guide(
            target = "Legs, glutes, and balance",
            equipment = "One or two dumbbells",
            first = "Hold the weights securely and take a stable split stance.",
            second = "Lower between both feet while keeping the front foot fully planted.",
            third = "Drive through the front foot to rise, then change sides after the set.",
            mistake = "Taking a stance so narrow that balance or knee alignment is lost.",
        ),
        "db_close_grip_floor_press" to guide(
            target = "Chest, shoulders, and triceps",
            equipment = "Two dumbbells and floor",
            first = "Lie down with knees bent and hold the dumbbells close above your chest.",
            second = "Lower the upper arms until they meet the floor gently.",
            third = "Press upward while keeping wrists straight and the weights controlled.",
            mistake = "Bouncing the arms from the floor or letting the wrists bend backward.",
        ),
        "db_two_arm_row" to guide(
            target = "Upper back and arms",
            equipment = "Two dumbbells",
            first = "Hinge at the hips with soft knees and let both dumbbells hang.",
            second = "Keep a long spine as you pull both elbows toward your hips.",
            third = "Pause briefly, then lower both weights under control.",
            mistake = "Standing up during each repetition or shrugging the shoulders.",
        ),
        "db_sumo_deadlift" to guide(
            target = "Glutes, legs, and back",
            equipment = "One dumbbell",
            first = "Stand wider than hip-width and hold one dumbbell securely between your legs.",
            second = "Push the hips back and bend the knees while keeping the chest comfortable.",
            third = "Press the floor away to stand tall, keeping the weight close.",
            mistake = "Rounding the back or letting the knees collapse inward.",
        ),
        "db_single_arm_press" to guide(
            target = "Shoulders, triceps, and core",
            equipment = "One dumbbell and stable seat",
            first = "Sit tall with both feet planted and hold one dumbbell at shoulder height.",
            second = "Brace gently and press overhead without leaning to the other side.",
            third = "Lower with control, finish the side, then switch arms.",
            mistake = "Leaning or arching the back to move a weight that is too heavy.",
        ),
        "suitcase_carry" to guide(
            target = "Grip, core, shoulders, and balance",
            equipment = "One dumbbell",
            first = "Hold one dumbbell at your side and stand tall with level shoulders.",
            second = "Walk with short controlled steps without leaning toward or away from it.",
            third = "Set the weight down safely, then repeat on the other side.",
            mistake = "Letting the weight pull the torso sideways or swing while walking.",
        ),
        "hack_squat" to guide(
            target = "Legs and glutes",
            equipment = "Hack squat machine",
            first = "Set your shoulders and back against the pads with feet planted securely.",
            second = "Release the safety and lower only through a range you can control.",
            third = "Press evenly through both feet without forcefully locking the knees.",
            mistake = "Lowering until the hips lift from the pad or the heels lose contact.",
        ),
        "cable_chest_press" to guide(
            target = "Chest, shoulders, triceps, and core",
            equipment = "Cable machine",
            first = "Take a stable staggered stance with handles held near the chest.",
            second = "Brace your torso and press both handles forward without shrugging.",
            third = "Return the handles slowly while maintaining your stance.",
            mistake = "Using body momentum or allowing the cables to pull the shoulders back abruptly.",
        ),
        "assisted_pull_up" to guide(
            target = "Upper back and arms",
            equipment = "Assisted pull-up machine",
            first = "Set enough assistance and place your hands and knees or feet securely.",
            second = "Pull your chest upward while keeping the shoulders away from the ears.",
            third = "Lower slowly until the arms are long, then repeat without bouncing.",
            mistake = "Dropping quickly into the bottom or swinging to create momentum.",
        ),
        "chest_supported_row" to guide(
            target = "Upper back and arms",
            equipment = "Chest-supported row machine",
            first = "Adjust the seat so your chest is supported and the handles are reachable.",
            second = "Pull the handles toward you while keeping the chest against the pad.",
            third = "Straighten the arms slowly without letting the weight stack slam.",
            mistake = "Lifting the chest from the pad or shrugging during the pull.",
        ),
        "seated_hamstring_curl" to guide(
            target = "Back of the thighs",
            equipment = "Seated hamstring curl machine",
            first = "Align your knees with the machine pivot and secure the thigh pad.",
            second = "Curl the lower legs down using the back of the thighs.",
            third = "Pause briefly, then return slowly until the knees are nearly straight.",
            mistake = "Lifting the hips or allowing the weight to snap back.",
        ),
        "pallof_hold" to guide(
            target = "Core and anti-rotation control",
            equipment = "Cable machine",
            first = "Stand sideways to the cable and hold the handle at your chest.",
            second = "Press the hands forward and hold without allowing your torso to turn.",
            third = "Bring the handle back slowly, then repeat on the other side.",
            mistake = "Holding your breath or letting the shoulders rotate toward the cable.",
        ),
        "heel_dig" to guide(
            target = "Cardio, legs, and coordination",
            equipment = "Bodyweight",
            first = "Stand tall with soft knees and enough clear space around you.",
            second = "Place one heel forward lightly while the opposite arm swings.",
            third = "Return to center and alternate sides at a steady pace.",
            mistake = "Leaning backward or striking the heel hard against the floor.",
        ),
        "side_step_reach" to guide(
            target = "Cardio, hips, and shoulders",
            equipment = "Bodyweight",
            first = "Stand tall with feet together and arms relaxed.",
            second = "Step to one side while sweeping both arms through a comfortable reach.",
            third = "Step back to center and repeat smoothly to the other side.",
            mistake = "Crossing the feet or forcing the shoulders into a painful range.",
        ),
        "sit_to_stand_reach" to guide(
            target = "Legs, glutes, shoulders, and cardio",
            equipment = "Stable chair",
            first = "Sit near the front of a stable chair with feet planted.",
            second = "Lean forward slightly and press through the feet to stand.",
            third = "Reach comfortably overhead, then lower and sit with control.",
            mistake = "Dropping onto the chair or using momentum to throw the arms upward.",
        ),
        "standing_knee_drive" to guide(
            target = "Cardio, hips, core, and balance",
            equipment = "Stable support if needed",
            first = "Stand tall with hands forward or resting lightly on a support.",
            second = "Drive one knee upward while keeping your torso controlled.",
            third = "Lower softly and alternate sides at a sustainable pace.",
            mistake = "Leaning far backward or stamping the foot down.",
        ),
        "lateral_toe_tap" to guide(
            target = "Cardio, hips, and balance",
            equipment = "Bodyweight",
            first = "Stand with knees soft and your weight centered.",
            second = "Shift onto one leg and tap the other foot lightly to the side.",
            third = "Return through center and alternate sides with quiet steps.",
            mistake = "Twisting the planted knee or reaching farther than you can control.",
        ),
        "wall_walkout" to guide(
            target = "Full body, shoulders, core, and cardio",
            equipment = "Clear wall",
            first = "Stand facing a wall and place both hands around chest height.",
            second = "Walk the hands downward as you step back only through a controllable range.",
            third = "Walk the hands back up and step forward to stand tall.",
            mistake = "Walking too low until the back sags or the feet begin to slip.",
        ),
        "seated_cat_cow" to guide(
            target = "Spine and trunk mobility",
            equipment = "Stable chair",
            first = "Sit tall with feet planted and hands resting on the thighs.",
            second = "Exhale as you round the spine gently and let the head follow.",
            third = "Inhale as you lengthen and open the chest through a comfortable range.",
            mistake = "Forcing the neck or making the movement only in the lower back.",
        ),
        "half_kneeling_stretch" to guide(
            target = "Front of the hip and thigh",
            equipment = "Floor or exercise mat",
            first = "Kneel on one knee with the other foot planted in front.",
            second = "Tuck the pelvis gently and shift forward until the rear hip feels a stretch.",
            third = "Hold while breathing normally, then change sides.",
            mistake = "Arching the lower back or pushing into pinching discomfort.",
        ),
        "seated_hip_rotation" to guide(
            target = "Hip mobility",
            equipment = "Stable chair",
            first = "Sit tall with feet planted and knees bent comfortably.",
            second = "Move one knee inward and outward slowly while the foot stays relaxed.",
            third = "Use a comfortable range, then repeat on the other side.",
            mistake = "Twisting the torso or forcing through a pinching sensation.",
        ),
        "shoulder_circle" to guide(
            target = "Shoulders and upper back mobility",
            equipment = "Bodyweight",
            first = "Stand or sit tall with ribs relaxed and arms by your sides.",
            second = "Make smooth shoulder circles upward, backward, and down.",
            third = "Reverse direction while keeping the neck relaxed.",
            mistake = "Moving too quickly or forcing a range that causes discomfort.",
        ),
        "wall_calf_stretch" to guide(
            target = "Calves and ankle mobility",
            equipment = "Clear wall",
            first = "Place both hands on a wall and step one foot behind you.",
            second = "Point both feet forward and keep the back heel planted.",
            third = "Lean forward gently, hold, then repeat on the other side.",
            mistake = "Turning the rear foot outward or bouncing into the stretch.",
        ),
        "forearm_wall_press" to guide(
            target = "Chest, shoulders, and triceps",
            equipment = "Clear wall",
            first = "Stand facing a wall and place both forearms against it around chest height.",
            second = "Keep your body long as you lean toward the wall through a comfortable range.",
            third = "Press through the forearms to return to standing with control.",
            mistake = "Arching the lower back or letting the shoulders shrug.",
        ),
        "standing_cross_crawl" to guide(
            target = "Core and coordination",
            equipment = "Stable chair or wall if needed",
            first = "Stand tall beside a stable support with your feet comfortable.",
            second = "Lift one knee as the opposite elbow moves toward it without forcing contact.",
            third = "Return slowly and alternate sides while breathing normally.",
            mistake = "Twisting quickly or leaning heavily into the support.",
        ),
        "standing_core_brace" to guide(
            target = "Core control",
            equipment = "Bodyweight",
            first = "Stand with stable feet, soft knees, and relaxed shoulders.",
            second = "Exhale gently and tighten your middle as if preparing for a light push.",
            third = "Hold the tension while breathing, then relax fully before repeating.",
            mistake = "Holding your breath or squeezing as hard as possible.",
        ),
        "db_chest_squeeze" to guide(
            target = "Chest and arms",
            equipment = "One light dumbbell",
            first = "Stand or sit tall and hold one dumbbell horizontally at chest height.",
            second = "Press both palms inward against the weight while keeping the shoulders relaxed.",
            third = "Maintain the squeeze for the prescribed time while breathing steadily.",
            mistake = "Shrugging the shoulders or holding your breath.",
        ),
        "db_lateral_raise" to guide(
            target = "Shoulders",
            equipment = "Two light dumbbells",
            first = "Stand tall with a light dumbbell at each side and elbows softly bent.",
            second = "Lift the arms out to the sides only to a comfortable height below the shoulders.",
            third = "Lower slowly until the weights return to your sides.",
            mistake = "Swinging the weights or shrugging to lift higher.",
        ),
        "supported_march" to guide(
            target = "Cardio and hips",
            equipment = "Stable chair, wall, or rail",
            first = "Stand tall beside a stable support and rest one hand on it lightly.",
            second = "Lift one knee through a comfortable range, then place the foot down softly.",
            third = "Alternate sides at a steady pace while keeping your torso controlled.",
            mistake = "Pulling on the support or stamping the feet.",
        ),
        "supported_side_step" to guide(
            target = "Cardio and hips",
            equipment = "Stable chair, wall, or rail",
            first = "Stand facing a stable support with knees soft and feet parallel.",
            second = "Take a small step to one side, then bring the other foot toward it.",
            third = "Continue with controlled steps, then change direction.",
            mistake = "Crossing the feet or twisting the knees.",
        ),
        "supported_knee_drive" to guide(
            target = "Cardio, core, and hips",
            equipment = "Stable chair, wall, or rail",
            first = "Stand tall with one hand resting lightly on a stable support.",
            second = "Drive one knee upward while keeping your ribs stacked over your hips.",
            third = "Lower softly, alternate sides, and keep a sustainable pace.",
            mistake = "Leaning far backward or pulling against the support.",
        ),
        "supported_lateral_tap" to guide(
            target = "Hips, balance, and cardio",
            equipment = "Stable chair, wall, or rail",
            first = "Stand beside a stable support with your weight centered.",
            second = "Shift onto one leg and tap the other foot a short distance to the side.",
            third = "Return to center and alternate sides with quiet, controlled steps.",
            mistake = "Twisting the planted knee or reaching too far.",
        ),
        "standing_hip_flexor_stretch" to guide(
            target = "Front of the hip and thigh",
            equipment = "Clear wall or stable chair",
            first = "Stand beside a support and take a comfortable split stance.",
            second = "Tuck the pelvis gently and shift your weight forward a small amount.",
            third = "Hold the stretch while breathing normally, then change sides.",
            mistake = "Arching the lower back or forcing a pinching range.",
        ),
        "shoulder_blade_squeeze" to guide(
            target = "Upper back and posture",
            equipment = "Bodyweight",
            first = "Sit or stand tall with your arms relaxed by your sides.",
            second = "Draw the shoulder blades gently back and slightly down.",
            third = "Pause without holding your breath, then release fully.",
            mistake = "Shrugging the shoulders or forcing the chest forward.",
        ),
        "seated_breathing" to guide(
            target = "Breathing and recovery",
            equipment = "Stable chair",
            first = "Sit with your back supported and both feet planted comfortably.",
            second = "Breathe in slowly through the nose and let the ribs expand gently.",
            third = "Exhale without forcing, allowing the shoulders and jaw to relax.",
            mistake = "Taking strained breaths or deliberately holding the breath.",
        ),
        "knee_to_chest" to guide(
            target = "Hips, lower back, and relaxed breathing",
            equipment = "Floor or exercise mat",
            first = "Lie on your back with both knees bent and feet relaxed.",
            second = "Bring one knee toward the chest and hold behind the thigh or over the shin.",
            third = "Breathe slowly, release gently, then change sides.",
            mistake = "Pulling forcefully or lifting the head and shoulders with tension.",
        ),
    )

    fun forExercise(exercise: Exercise): ExerciseGuide =
        guides[exercise.id] ?: ExerciseGuide(
            targetArea = "Full-body movement",
            equipment = "Follow today's plan",
            steps = listOf(
                "Set up in a stable position with enough clear space.",
                "Move slowly through a comfortable range while breathing normally.",
                "Stop the set before control or technique begins to change.",
            ),
            commonMistake = "Rushing the movement or using a range you cannot control.",
        )

    fun hasGuide(exerciseId: String): Boolean = exerciseId in guides

    private fun guide(
        target: String,
        equipment: String,
        first: String,
        second: String,
        third: String,
        mistake: String,
    ) = ExerciseGuide(
        targetArea = target,
        equipment = equipment,
        steps = listOf(first, second, third),
        commonMistake = mistake,
    )
}
